fix: github main.yml

diff --git a/.github/workflows/main.yml b/.github/workflows/main.yml
--- a/.github/workflows/main.yml
+++ b/.github/workflows/main.yml
@@ -1,13 +1,23 @@
-name: Action Branch Check
+name: Branch Check
 
 on:
   pull_request:
-    branches: [stage]
+    branches:
+      - master
+      - stage
+      - dev
 
 jobs:
-  deploy:
+  branch_check:
     runs-on: ubuntu-latest
-    if: github.ref != 'refs/heads/stage_test'
     steps:
-      - name: Deploy app 
-        run: exit 1
+      - name: check branches
+        #if: (github.base_ref == 'master' && github.head_ref != 'stage') || (github.base_ref == 'stage' && github.head_ref != 'dev')
+        run: |
+        if [ $github.base_ref = 'master' ] && [ $github.head_ref != 'stage' ]; then echo "error" && exit 1; else exit 0; fi
+        #echo "source:" ${{ github.head_ref }} "target:" ${{ github.base_ref }} "It's not available branch. (dev->stage->master)" && exit 1
+        #- name: success
+        #if: ${{ success() }}
+        #run: exit 0
+        #  build:
+        #    need: branch_check
